# Generated by Django 3.1 on 2020-08-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logbook',
            name='creation_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date created'),
        ),
    ]
