# Generated by Django 3.1 on 2020-08-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='darkmode',
            field=models.BooleanField(default=False),
        ),
    ]
